"""
ml_drift_detector.py – ML drift detector (minimum viable implementation, Task 2.1).

Monitors the distribution of ML predictions over a rolling window
and alerts when significant drift from baseline is detected.

LIMITATIONS:
- record_result() and calibration tracking are deferred to Task 3.1.
- baseline_distribution.json is expected at models/ but not yet generated
  by train_model.py. Without it, only stats are computed, KL is skipped.
- The detector is operational only when ML_DISABLED_MODE = False
  (i.e., post-Task 3.1 when ML is reactivated).

See CHANGELOG_REMEDIATION.md for full deferred scope.
"""
from __future__ import annotations

import json
import logging
import os
from collections import deque
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np

logger = logging.getLogger(__name__)

# ─── Logger JSONL para drift ─────────────────────────────────────────────────

_drift_logger = logging.getLogger("ml_drift")
_drift_log_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "logs")
os.makedirs(_drift_log_dir, exist_ok=True)
_drift_handler = logging.FileHandler(
    os.path.join(_drift_log_dir, "ml_drift.log"), encoding="utf-8"
)
_drift_handler.setFormatter(logging.Formatter("%(message)s"))
_drift_logger.addHandler(_drift_handler)
_drift_logger.setLevel(logging.INFO)

# ─── Paths ───────────────────────────────────────────────────────────────────

BASELINE_PATH = Path("models/baseline_distribution.json")


class DriftDetector:
    """
    Monitors ML prediction distribution for drift.

    Records predictions in a circular buffer of `window` size.
    Every `check_every` predictions, computes distribution stats
    and KL divergence against baseline (if available).
    """

    def __init__(
        self,
        window: int = 100,
        check_every: int = 10,
        kl_threshold: float = 0.15,
    ) -> None:
        self._window = window
        self._check_every = check_every
        self._kl_threshold = kl_threshold
        self._buffer: deque = deque(maxlen=window)
        self._prediction_count: int = 0
        self._baseline: Optional[np.ndarray] = None
        self._baseline_loaded: bool = False
        self._alerts: List[Dict] = []

    # ── Baseline ─────────────────────────────────────────────────────────────

    def load_baseline(self, path: Path = BASELINE_PATH) -> bool:
        """Load baseline distribution from JSON (generated by train_model.py)."""
        if not path.exists():
            logger.debug(f"[ML_DRIFT] Baseline not found at {path}. KL skipped.")
            return False
        try:
            data = json.loads(path.read_text())
            self._baseline = np.array(data["bins"], dtype=float)
            self._baseline_loaded = True
            logger.info(f"[ML_DRIFT] Baseline loaded from {path} ({len(self._baseline)} bins).")
            return True
        except Exception as exc:
            logger.warning(f"[ML_DRIFT] Error loading baseline: {exc}")
            return False

    # ── Recording ────────────────────────────────────────────────────────────

    def record_prediction(
        self,
        call_proba: float,
        put_proba: float,
        asset: str = "",
    ) -> None:
        """Record a prediction in the circular buffer."""
        self._buffer.append({
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "call_proba": call_proba,
            "put_proba": put_proba,
            "asset": asset,
        })
        self._prediction_count += 1

        if self._prediction_count % self._check_every == 0 and len(self._buffer) >= self._check_every:
            self._check_drift()

    # ── Drift check ──────────────────────────────────────────────────────────

    def _check_drift(self) -> None:
        """Evaluate distribution stats and KL divergence."""
        stats = self._compute_stats()
        kl = None

        # Lazy load baseline on first check
        if not self._baseline_loaded:
            self.load_baseline()

        if self._baseline is not None and len(self._buffer) >= 20:
            observed = self._discretize()
            kl = self._kl_divergence(observed, self._baseline)

            if kl > self._kl_threshold:
                alert = {
                    "type": "KL_DIVERGENCE",
                    "kl_value": round(kl, 4),
                    "threshold": self._kl_threshold,
                    "buffer_size": len(self._buffer),
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                }
                self._alerts.append(alert)
                logger.warning(
                    f"[ML_DRIFT] KL divergence alert: {kl:.4f} > {self._kl_threshold} "
                    f"(buffer={len(self._buffer)})"
                )

        # Log JSONL
        try:
            entry = {
                "timestamp_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                "prediction_count": self._prediction_count,
                "buffer_size": len(self._buffer),
                "stats": stats,
                "kl_divergence": round(kl, 4) if kl is not None else None,
                "kl_alert": kl is not None and kl > self._kl_threshold,
            }
            _drift_logger.info(json.dumps(entry, separators=(",", ":")))
        except Exception:
            pass

    # ── Stats ────────────────────────────────────────────────────────────────

    def _compute_stats(self) -> Dict:
        """Compute distribution statistics of recent predictions."""
        if not self._buffer:
            return {}

        # Use the max of call/put proba (the "chosen" direction proba)
        probas = np.array([max(r["call_proba"], r["put_proba"]) for r in self._buffer])

        return {
            "mean": round(float(np.mean(probas)), 4),
            "std": round(float(np.std(probas)), 4),
            "p25": round(float(np.percentile(probas, 25)), 4),
            "p50": round(float(np.percentile(probas, 50)), 4),
            "p75": round(float(np.percentile(probas, 75)), 4),
            "min": round(float(np.min(probas)), 4),
            "max": round(float(np.max(probas)), 4),
            "count": len(probas),
        }

    def _discretize(self, n_bins: int = 10) -> np.ndarray:
        """Discretize buffer probabilities into histogram bins [0.0, 0.1, ..., 0.9, 1.0]."""
        probas = np.array([max(r["call_proba"], r["put_proba"]) for r in self._buffer])
        counts, _ = np.histogram(probas, bins=n_bins, range=(0.0, 1.0))
        return counts.astype(float) / counts.sum()

    # ── KL divergence ────────────────────────────────────────────────────────

    @staticmethod
    def _kl_divergence(observed: np.ndarray, baseline: np.ndarray) -> float:
        """
        KL(observed || baseline) with epsilon smoothing.

        Uses 1e-10 epsilon to avoid log(0) and division by zero.
        Both distributions are renormalized after smoothing.
        """
        eps = 1e-10
        p = observed + eps
        q = baseline + eps
        p = p / p.sum()
        q = q / q.sum()
        return float(np.sum(p * np.log(p / q)))

    # ── Public API ───────────────────────────────────────────────────────────

    def get_metrics(self) -> Dict:
        """Snapshot of current drift metrics for dashboard/API."""
        stats = self._compute_stats()
        return {
            "prediction_count": self._prediction_count,
            "buffer_size": len(self._buffer),
            "window": self._window,
            "stats": stats,
            "baseline_loaded": self._baseline_loaded,
            "kl_threshold": self._kl_threshold,
            "recent_alerts": self._alerts[-5:],
        }


# ─── Singleton ────────────────────────────────────────────────────────────────

drift_detector = DriftDetector()
